name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHB_TOKEN }}

      - uses: actions/checkout/@v3
      - name: Build & Push action
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ghcr.io/mharikmert/infra-svg-server:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/mharikmert/infra-svg-server:latest
